# Setup
title: Apprenticeship Blog
tagline: My thoughts and experiences as an 8th Light Apprentice
baseurl: ""
paginate: 1

# About/contact
author:
  name: Jason Desrosiers
  url: https://github.com/jdesrosiers

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
