# Setup
title: My Blog
tagline: A short description of my blog
baseurl: ""
paginate: 1

# About/contact
author:
  name: Jason Desrosiers
  url: https://github.com/jdesrosiers

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
